<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	targetNamespace="http://gcsoftware.anagrafica/services/SubjectService/"
	xmlns:tns="http://gcsoftware.anagrafica/services/SubjectService/" xmlns:subject="http://gcsoftware.anagrafica/entities/Subject"
	name="SubjectService">

	<wsdl:types>
		<xsd:schema targetNamespace="http://gcsoftware.anagrafica/services/SubjectService/">
			<xsd:import namespace="http://gcsoftware.anagrafica/entities/Subject"
				schemaLocation="subject.xsd" />
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="SubjectRequest">
		<wsdl:part element="subject:SubjectRequestType" name="parameters" />
	</wsdl:message>
	<wsdl:message name="SubjectResponse">
		<wsdl:part element="subject:SubjectResponseType" name="parameters" />
	</wsdl:message>

	<wsdl:portType name="ISubjectService">
		<wsdl:operation name="getSubjectByISDNRequestNumber">
			<wsdl:input message="tns:SubjectRequest" />
			<wsdl:output message="tns:SubjectResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="SubjectServiceSOAPBinding" type="tns:ISubjectService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getSubjectByISDNRequestNumber">
			<soap:operation soapAction="" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="SubjectService">
		<wsdl:port name="SubjectServicePort" binding="tns:SubjectServiceSOAPBinding">
			<soap:address
				location="http://localhost:9080/gcsoftwareanagrafica/services/SubjectService" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>